source :rubygems
ruby '1.9.3'

# Server
gem 'unicorn'

# App
gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'erubis'

# Development
group :development do
  gem 'awesome_print'
end

# Assets
group :assets do
  gem 'sprockets'
  gem 'coffee-script'
  gem 'stylus'
  gem 'yui-compressor', :require => 'yui/compressor'
  gem 'uglifier'
end
